#!/bin/csh
echo "-- Testing your implementation of malloc --"
echo ""
echo "- If you have any problem in passing a test read the corresponding"
echo "- source file to understand what the test is checking"
echo ""
printf "********************* TEST MERGE ********************* \n"
./tstmerge
printf "********************* TEST ALGORITHMS ********************* \n"
./tstalgorithms
printf "********************* TEST EXTREME USAGE ********************* \n"
./tstextreme
printf "********************* TEST MALLOC ********************* \n"
./tstmalloc
printf "********************* TEST MEMORY ********************* \n"
./tstmemory
printf "********************* TEST REALLOC ********************* \n"
./tstrealloc 
printf "********************* TEST MALLOC (STEADY) ********************* \n"
./tststeady 10000
printf "********************* TEST MALLOC (INCREASING) ********************* \n"
./tstincrement 10000
printf "********************* TEST FRAGMENT ********************* \n"
./tstfragment 10000
echo "All test executed"
